my second task
reiniergs/starters-step-1 pull request #4
Opened 2018-01-24 22:00 UTC by cmcartaya

2018-01-25 00:18 UTC, reiniergs requested changes

2018-01-25 00:18 UTC, reiniergs commented on cartaya/2/style.css
> +#people-search {
you shouldn't never ever use css selector for element id, use classes

2018-01-25 00:18 UTC, reiniergs commented on cartaya/2/style.css
> +label {
you shouldn't never ever use css selector for element name, use classes ... there reason behind this is that when you apply styles directly to an element, it means all element label in you website have applied the same styles

2018-01-25 00:18 UTC, reiniergs commented
fix the conflits as well

2018-01-31 03:44 UTC, TahimiLeonBravo commented on cartaya/2/task2.html
> +                <input class="selector-azul" checked type="radio" id="last-name" name="people-search" value="last-name" aria-label="last name">
You need always use a convention to the names of all classes, it should create collisions.

2018-01-31 03:44 UTC, TahimiLeonBravo commented on cartaya/2/task2.html
> +        <section class="perfil">
You need always use a convention to the names of all classes, it should create collisions.

2018-01-31 03:44 UTC, TahimiLeonBravo commented on cartaya/2/style.css
> +}
You have to add a newline at the end of the file

2018-01-31 03:44 UTC, TahimiLeonBravo commented on cartaya/2/task2.html
> +</html>
You have to add a new line at the end of the file

2018-01-31 03:44 UTC, TahimiLeonBravo commented on cartaya/2/task2.html
> +        <span id="h1">Intranet</span>
Never use the attribute id for elements name, use class. the id is a global attribute that defines a unique identifier which must be unique in the whole document.

2018-01-31 03:44 UTC, TahimiLeonBravo commented on cartaya/2/style.css
> +    font-family: HelveticaNeueCE35Thin;
You can define the font-family property in the element container, this is an Inherited property you don’t need specify in each element inside the container. If all the texts in the document have the same font, define this property only in the general element container.

2018-02-02 23:19 UTC, TahimiLeonBravo approved these changes

2018-02-03 09:05 UTC, TahimiLeonBravo approved these changes

2018-02-03 19:28 UTC, TahimiLeonBravo approved these changes

2018-02-03 19:28 UTC, closed without merging