this is my first task
reiniergs/starters-step-1 pull request #5
Opened 2018-01-24 22:02 UTC by cmcartaya

2018-01-25 00:23 UTC, reiniergs requested changes

2018-01-25 00:23 UTC, reiniergs commented on cartaya/1/style.css
> +div.txt {
div.text === .text ??? there are not the same I know but don't do that, avoid to use element selectors

2018-01-25 00:23 UTC, reiniergs commented on cartaya/1/style.css
> +img {
element selector !!

2018-01-25 00:23 UTC, reiniergs commented on cartaya/1/style.css
> +a {
element selector

2018-01-31 04:04 UTC, TahimiLeonBravo commented on cartaya/1/task.html
> +            <br /><br />
Don’t  use ```<br />```  tag to increase the gap between lines of text; use the CSS margin  property

2018-01-31 04:04 UTC, TahimiLeonBravo commented on cartaya/1/task.html
> +        <div class="img">
You need always use a convention to the names of all classes, it should create collisions.

2018-01-31 04:04 UTC, TahimiLeonBravo commented on cartaya/1/task.html
> +</html>
You have to add a new line at the end of the file

2018-01-31 04:04 UTC, TahimiLeonBravo commented on cartaya/1/style.css
> +    color: rgba(255, 255, 255, 0.877);
You can define the color in the element container, this is an Inherited property you don’t need specify in each element inside container

2018-01-31 04:13 UTC, TahimiLeonBravo commented on cartaya/1/task.html
> +            <br /><br />
The main reason for not using ```<br>``` is that it's not semantic. If you want two items in different visual blocks, you probably want them in different logical blocks.

2018-02-03 19:28 UTC, closed without merging