4th task
reiniergs/starters-step-1 pull request #6
Opened 2018-01-24 22:22 UTC by cmcartaya

2018-01-25 00:24 UTC, reiniergs requested changes

2018-01-25 00:24 UTC, reiniergs commented on cartaya/4/style4.css
> +fieldset  div  img {
element selector

2018-01-31 04:43 UTC, TahimiLeonBravo commented on cartaya/4/task4.html
> +        <div class="profile-img"><img src="perfil.png" alt="profile picture" title="profile" height="152px" width="150.5"></div>
That is not readable you need to put it in this way instead:
```
<div class="profile-img">
    <img src="perfil.png" alt="profile picture" title="profile" height="152px" width="150.5">
</div>
```

2018-01-31 04:43 UTC, TahimiLeonBravo commented on cartaya/4/task4.html
> +    <section class="section-left">
You need always use a convention to the names of all classes, it should create collisions.

2018-01-31 04:43 UTC, TahimiLeonBravo commented on cartaya/4/task4.html
> +                <div class="profile-data-img"><img src="1.png" alt="name" width="25px" height="15px"></div>
Don't use the width and height attribute intead use CSS styles. We need to follow the separation of concerns principle, the styles always in CSS.

2018-01-31 04:43 UTC, TahimiLeonBravo commented on cartaya/4/style4.css
> +    font-family: HelveticaNeueCE35Thin;
You can define the font-family property  in the element container, this is a Inherited property you don’t need specify in each element inside container. If all the texts in the document have the same font, define this property only in the body or element container.

2018-01-31 04:43 UTC, TahimiLeonBravo commented on cartaya/4/style4.css
> +.h1-profile-name {
Don't use the HTML elements name for classes name.

2018-02-02 23:13 UTC, TahimiLeonBravo approved these changes

2018-02-03 19:29 UTC, closed without merging