message page by cartaya
reiniergs/starters-step-1 pull request #77
Opened 2018-02-23 02:39 UTC by cmcartaya

2018-02-23 06:57 UTC, sarayp requested changes

2018-02-23 06:57 UTC, sarayp commented on cartaya/message-page/resources/css/styles.css
> +.message_fotter {
there is a typo (footer)

2018-02-23 06:57 UTC, sarayp commented on cartaya/message-page/resources/css/styles.css
> +}
indent above

2018-02-23 06:57 UTC, sarayp commented on cartaya/message-page/resources/css/styles.css
> +}
indent above

2018-02-23 06:57 UTC, sarayp commented on cartaya/message-page/resources/css/styles.css
> +}
indent above

2018-02-23 06:57 UTC, sarayp commented on cartaya/message-page/resources/css/styles.css
> +    font-family: 'Camphor-Thin', 'Arial', sans-serif;
font-face is defining lato-regular. Here you are declaring camphor-thin...which one it is?

2018-02-24 20:41 UTC, TahimiLeonBravo approved these changes

2018-02-25 00:56 UTC, sarayp approved these changes

2018-02-25 00:56 UTC, merged