social page from cartaya
reiniergs/starters-step-1 pull request #80
Opened 2018-02-26 08:31 UTC by cmcartaya

2018-02-26 19:21 UTC, sarayp requested changes

2018-02-26 19:21 UTC, sarayp commented on cartaya/social-page/index.html
> +                <input class="socialpg_input-mail" type="email" name="email" placeholder="Enter your email address">
need to define an id attribute to the input and bind it to the label for accessibility.... we should always define id and for.

2018-02-28 07:00 UTC, sarayp submitted a review, later dismissed

2018-02-28 07:00 UTC, sarayp commented on cartaya/social-page/index.html
> +            <label class="socialpg_text-befor-mail">
this label tag is the label and should be the one connected to the one using the _for_ attribute

2018-02-28 07:00 UTC, sarayp commented on cartaya/social-page/index.html
> +            <label class="socialpg_input-mail-container" for="mail">
This label tag is acting as a container

2018-02-28 20:51 UTC, TahimiLeonBravo approved these changes

2018-03-01 00:50 UTC, reiniergs requested changes

2018-03-01 00:50 UTC, reiniergs commented on cartaya/social-page/index.html
> +            </label>
there is an issue here with `a11y` when the input gets the focus the screen reader is gonna try to read the text inside the label the input is linked to. there isn't text  with the label here. I assume the text you want to be read is  `Provide your email address &amp; we will send you our newsletter` but there is no clear relationship in between the input and that text.

2018-03-03 06:46 UTC, reiniergs approved these changes
LGTM

2018-03-03 06:47 UTC, merged