get your gift by cartaya
reiniergs/starters-step-1 pull request #85
Opened 2018-03-03 09:10 UTC by cmcartaya

2018-03-04 10:13 UTC, TahimiLeonBravo approved these changes

2018-03-08 18:50 UTC, sarayp requested changes

2018-03-08 18:50 UTC, sarayp commented on cartaya/get-your-gift/index.html
> +                <div class="tep-gift_input-divider"></div>
should be consistent with class naming...(step-gift)

2018-03-08 19:00 UTC, sarayp requested changes

2018-03-08 19:00 UTC, sarayp commented on cartaya/get-your-gift/index.html
> +                <div class="tep-gift_input-divider"></div>
should be consistent with class naming...(step-gift)

2018-04-03 01:08 UTC, sarayp approved these changes

2018-04-03 01:08 UTC, merged